### ISSUE TITLE
Disable automatic conversion of integers to list indices?

### ISSUE THREAD

**Issue by theRealSuperMario** [dpath-maintainers/dpath-python#140]
Hi,

I just wanted to ask if there is any way to disable integers becoming list indices with the tree?

hence "a/b/1" would become 
```python
{
  a: {
      b: {
      1: "foo"
     }
 }
}
```

**Comment by moomoohk** [comment]
Hi Sandro,
I'm not sure I understand what you mean. Would you mind including some code to describe your question?

**Comment by moomoohk** [comment]
Closed due to inactivity (I'm also assuming this issue is resolved in newer versions).
