### ISSUE TITLE
critical error when key starts by zeros

### ISSUE THREAD

**Issue by cybermed-ai** [dpath-maintainers/dpath-python#148]
import dpath.util

d = {
    'a': 5,
    '0': 4,
    '9': 99,
    '60080008': 'hello 1',
    '00080008': 'hello 2'
}

print(dpath.util.get(d, 'a'))
print(dpath.util.get(d, '0'))
print(dpath.util.get(d, '9'))
print(dpath.util.get(d, '60080008'))
print(dpath.util.get(d, '00080008'))

we get an error "KeyError: '00080008'"

it is due to an attempt to convert integer segments into actual integers in file .venv/lib/python3.9/site-packages/dpath/util.py
 line 34:

# Attempt to convert integer segments into actual integers.
        final = []
        for segment in segments:
            try:
                final.append(int(segment))
            except:
                final.append(segment)
        segments = final

why this piece of code ? why not let us use keys starting with zeros?

if i could change my keys to be "80008" instead of "00080008" I would do it but it is very complicated since we want to use dpath library to query dict by path and our dicts belongs to DICOM (medical images) technologies and this is the way we specified tags in DICOM. If I simplified the way they store key/values I will loss interoperability with other external systems

so, I'm a bit disappointed. anything we can do ?

**Comment by moomoohk** [comment]
Hi,
I've added a new options that allows control over this behavior:
```python
>>> dpath.options.CONVERT_INT_LIKE_SEGMENTS = False
>>> d = {'a': 5,'0': 4,'9': 99,'60080008': 'hello 1','00080008': 'hello 2'}
>>> dpath.util.get(d, '00080008')
'hello 2'
```

This change will hit PyPI soon, stay tuned.
