### ISSUE TITLE
Disable creating empty list elements 

### ISSUE THREAD

**Issue by pavel-koko** [dpath-maintainers/dpath-python#158]
`@>>> hash = {}`
`@>>> path = 'a/3/c'`
`@>>> dpath.util.new(hash, path, [1,2,3])`
`{'a': [None, None, None, {'c': [1, 2, 3]}]`

What can i do, if i do not want the list with the 3 empty elements? I would like the path to lead to the same result, als if 'b' is part of path instead of '3'

`{'a': {'b': {'c': [1, 2, 3]}}}`

**Comment by moomoohk** [comment]
Hi Pavel,
See #160. If I'm understanding correctly, the solution there will answer your question as well:

```python
def dict_creator(current, segments, i, hints=()):
    segment = segments[i]

    if isinstance(segment, int):
        dpath.segments.extend(current, segment)

    # Infer the type from the hints provided.
    if i < len(hints):
        current[segment] = hints[i][1]()
    else:
        current[segment] = {}


x={}
dpath.util.new(x, 'a/3/c', [1, 2, 3], creator=dict_creator)
```

Should result in:
`{'a': {3: {'c': [1, 2, 3]}}}`

Please let me know if this works for you.
