### ISSUE TITLE
Handle int as key in path

### ISSUE THREAD

**Issue by benoit-cty** [dpath-maintainers/dpath-python#160]
Hello,

After upgrading our dependencies for dpath in https://github.com/openfisca/openfisca-core we have an error because dpath don't work the same way in 2.0.5 as in 1.5.0. It's due to the feature introduced by https://github.com/dpath-maintainers/dpath-python/issues/91
But as we use integer as key for year, or code does not work. Well, not integer as the key is "2017", so it is a string, not an integer. But when we write it in path, dpath use it as an int, not a string.
Did you know if there is a way to have the same behavior as in 1.5.0 ?

Old behavior:
```
>>> x={};dpath.util.new(x,'path/that/not/exist/2', 42)
{'path': {'that': {'not': {'exist': {'2': 42}}}}}
```

New behavior:
```
>>> x={};dpath.util.new(x,'path/that/not/exist/2', 42)
{'path': {'that': {'not': {'exist': [None, None, 42]}}}}
```

The workaround I found is to create the path before calling `new`:
```
>>> x={'path': {'that':{'not':{'exist':{2:None}}}}};
>>> dpath.util.new(x,'path/that/not/exist/2', 42)
{'path': {'that': {'not': {'exist': {2: 42}}}}}

```

But it's not the same, as I have to use 2 and not '2' as key. And our key is string '2017', not integer 2017.

**Comment by moomoohk** [comment]
Hi Benoit,
This is a tough issue to tackle since `int`s in paths are ambiguous: They can signify indices of a list as well as keys in a dict.
It would appear that pre-1.5.0 the default behavior was to treat them as list indices, which is what you're expecting.
I'm checking whether there's an existing simple way to configure that default behavior. If not I will consider adding some configurability.
All that said, I do think your workaround is quite elegant (considering the complexity of the causing issue).
Will update.

**Comment by moomoohk** [comment]
That took less time than expected :)
Please try the following:

```python
def dict_creator(current, segments, i, hints=()):
    segment = segments[i]

    if isinstance(segment, int):
        extend(current, segment)

    # Infer the type from the hints provided.
    if i < len(hints):
        current[segment] = hints[i][1]()
    else:
        current[segment] = {}


x={}
dpath.util.new(x,'path/that/not/exist/2', 42, creator=dict_creator)
```

Should result in:
`{'path': {'that': {'not': {'exist': {'2': 42}}}}}`

This method indeed overrides the default creator behavior by removing any special treatment of `int`s. It will always create dicts and never lists.

I will continue checking whether there is an improvement that can be made to the codebase based on this.

In the meantime, please let me know if this solution works for you.

**Comment by benoit-cty** [comment]
Hello,

Thanks for looking at it, but we still have a problem with merge:
```python
import dpath.util

def dict_creator(current, segments, i, hints=()):
    segment = segments[i]

    if isinstance(segment, int):
        dpath.segments.extend(current, segment)

    # Infer the type from the hints provided.
    if i < len(hints):
        current[segment] = hints[i][1]()
    else:
        current[segment] = {}


x={}
# dpath.util.new(x,'path/that/not/exist/2', 42, creator=dict_creator)

y={'path': {'that': {'exist': {'2': 50}}}}
dpath.util.new(x,'path/that/exist/2', 42, creator=dict_creator)
print(x)
print(y)
dpath.util.merge(y, x)
print(y)
```
Error:
```
$ python test_dpath.py 
{'path': {'that': {'exist': {2: 42}}}}
{'path': {'that': {'exist': {'2': 50}}}}
Traceback (most recent call last):
  File "/media/data/dev/src/LEXIMPACT/openfisca-core/.venv/lib/python3.8/site-packages/dpath/util.py", line 337, in merger
    target += found
TypeError: unsupported operand type(s) for +=: 'dict' and 'dict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/data/dev/src/LEXIMPACT/openfisca-core/.venv/lib/python3.8/site-packages/dpath/util.py", line 337, in merger
    target += found
TypeError: unsupported operand type(s) for +=: 'dict' and 'dict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/data/dev/src/LEXIMPACT/openfisca-core/.venv/lib/python3.8/site-packages/dpath/util.py", line 337, in merger
    target += found
TypeError: unsupported operand type(s) for +=: 'dict' and 'dict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_dpath.py", line 23, in <module>
    dpath.util.merge(y, x)
  File "/media/data/dev/src/LEXIMPACT/openfisca-core/.venv/lib/python3.8/site-packages/dpath/util.py", line 353, in merge
    merger(dst, filtered_src)
  File "/media/data/dev/src/LEXIMPACT/openfisca-core/.venv/lib/python3.8/site-packages/dpath/util.py", line 351, in merger
    merger(dst, found, segments)
  File "/media/data/dev/src/LEXIMPACT/openfisca-core/.venv/lib/python3.8/site-packages/dpath/util.py", line 351, in merger
    merger(dst, found, segments)
  File "/media/data/dev/src/LEXIMPACT/openfisca-core/.venv/lib/python3.8/site-packages/dpath/util.py", line 351, in merger
    merger(dst, found, segments)
  File "/media/data/dev/src/LEXIMPACT/openfisca-core/.venv/lib/python3.8/site-packages/dpath/util.py", line 293, in merger
    if len(key) == 0 and not options.ALLOW_EMPTY_STRING_KEYS:
TypeError: object of type 'int' has no len()
```

Nevermind, I will keep the workaround : We have upgraded dpath and I have handcoded the data insertion in the part concerned by the problem.
