### ISSUE TITLE
Error when merging 2 lists of dicts

### ISSUE THREAD

**Issue by kviktor** [dpath-maintainers/dpath-python#162]
I have this simple test program

```python
import dpath.util

a = [{"hello": "bello"}]
b = [{"just": "testing"}]
print(dpath.util.merge(a, b))
```

It gives the following error:
```
Traceback (most recent call last):
  File "/home/kviktor/test.py", line 5, in <module>
    print(dpath.util.merge(a, b))
  File "/home/kviktor/.local/lib/python3.10/site-packages/dpath/util.py", line 353, in merge
    merger(dst, filtered_src)
  File "/home/kviktor/.local/lib/python3.10/site-packages/dpath/util.py", line 293, in merger
    if len(key) == 0 and not options.ALLOW_EMPTY_STRING_KEYS:
TypeError: object of type 'int' has no len()
```

Removing https://github.com/dpath-maintainers/dpath-python/blob/master/dpath/util.py#L293-L296 fixes the issue but not sure if my case should even work.

**Comment by moomoohk** [comment]
Hi
I have addressed this issue in a similiar issue #131 . This behavior is currently unsupported. 

How would you recommend I make it clearer that this isn't a bug?

Additionally, if you find an easy way to achieve your goal please share.

**Comment by kviktor** [comment]
I know it's hard with Python but `TypeError: object of type 'int' has no len()` reads like a bug and not a feature. Maybe a custom dpath exception that says merging lists in unsupported?

**Comment by moomoohk** [comment]
Sounds good to me

**Comment by moomoohk** [comment]
Hi @kviktor 
Please try the revised code on the linked branch
