### ISSUE TITLE
Enable removing an element from a list instead of replacing with none

### ISSUE THREAD

**Issue by sherifnada** [dpath-maintainers/dpath-python#163]
Hi there

if I use `dpath.util.delete({“a”:[“a”, “b”]}, [“a”, 0])` the result is `{“a”:[None, “b”]} `. Is it possible to return `{“a”:[“b”]}` instead? 

The main workaround I can see is doing this externally by first examining if getting the second to last item in the input pointer returns a list and if so, remove that item from the list entirely. There will need to be some index management ti make sure consecutive requests cope with mutations to the underlying list (eg wanting to remove indices 0 and 3 becomes removing 0 and 2 since 3 was shifted down to 2 by the removal of 0). 

Any thoughts on whether this makes sense to add as an option here?

**Comment by moomoohk** [comment]
Hi Sherif
As you said, mutation during iteration creates an issue. I'm not sure I'm quite ready to tackle it at the moment.
Implementation suggestions are always welcome, as well as a PR of course :)

I can suggest a possible patchy workaround for you: In case you're expecting all non-`None` values in your dicts, you can manually filter them out after calling `dpath.util.delete`. Hope that helps.
