### ISSUE TITLE
glob search for multiple keys

### ISSUE THREAD

**Issue by albertbn** [dpath-maintainers/dpath-python#183]
hey, congrats on the great project - I've find it very useful

One thing I couldn't do: 

If I have:

```
x = {
    "a": {
        "b": {
            "3": 2,
            "43": 30,
            "cad": [],
            "dat": ['red', 'buggy', 'bumpers'],
        }
    }
}
```

I couldn't do this:

```
dpath.search(x, "a/b/['cad', 'dat']", yielded=True)
or 
dpath.search(x, "a/b/(cad|dat)", yielded=True)
or 
dpath.search(x, "a/b/{cad|dat}", yielded=True)

```

At this bash globbing resource they say it should be possible:

https://linuxhint.com/bash_globbing_tutorial/ see the **Curly bracket – ({})** section

Thanks
Albert

**Comment by albertbn** [comment]
thanks, I'll check it out

**Comment by moomoohk** [comment]
I'm closing this issue. Please feel free to reopen if needed.

Thanks for the help @MikeBiancalana. Great breakdown. Would you consider becoming more involved in the maintenance of this library? If so, please get in touch.

**Comment by Korben11** [comment]
It took me some time to figure out how to get all occurrences of a key globally.

In the XPath, if we are searching for `dat`, then we can do `//dat`.
I was expecting that `**dat` would return `['red', 'buggy', 'bumpers']`, but that is not the case.
It's necessary to add separator `.` after `**` => `**.dat` will return `['red', 'buggy', 'bumpers']`.

Maybe would be nice to add this case as an example to [README.rst](https://github.com/dpath-maintainers/dpath-python#readme)
