### ISSUE TITLE
Use dpath.new to insert keys which are integers as strings

### ISSUE THREAD

**Issue by permobergedge** [dpath-maintainers/dpath-python#199]
Hi,

How can I use dpath.new to create objects which has integers as keys, like in the example, how can I add "43" node:
```
x = {
    "a": {
        "b": {
            "3": 2,
            "43": 30,
            "c": [],
            "d": ['red', 'buggy', 'bumpers'],
        }
    }
}
```

I only get it interpreted as an integer and an array of size 43 is created.

Thanks

**Comment by moomoohk** [comment]
Please have a look at https://github.com/dpath-maintainers/dpath-python/issues/160#issuecomment-1027259408 and let me know if that helps.

**Comment by permobergedge** [comment]
Hi, 

Thanks for quick response and pointing me in the right direction.
That creator implementation solves the issue for me. :+1: 

/Per
